"""empty message

Revision ID: 1fb6a4d4de73
Revises: 
Create Date: 2022-06-26 19:41:03.390124

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1fb6a4d4de73'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe__tag',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('tag_id', sa.Integer(), nullable=False),
                    sa.Column('recipe_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
                    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('recipe_id', mysql.INTEGER(),
                  autoincrement=False, nullable=True))
    op.add_column('tag', sa.Column('skill_id', mysql.INTEGER(),
                  autoincrement=False, nullable=True))
    op.create_foreign_key('tag_ibfk_1', 'tag', 'recipe', ['recipe_id'], ['id'])
    op.create_foreign_key('tag_ibfk_2', 'tag', 'skill', ['skill_id'], ['id'])
    op.create_table('skill__step',
                    sa.Column('id', mysql.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('recipe_id', mysql.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('serial_number', mysql.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('instruction', mysql.TEXT(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['recipe_id'], ['skill.id'], name='skill__step_ibfk_1'),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_collate='utf8mb4_0900_ai_ci',
                    mysql_default_charset='utf8mb4',
                    mysql_engine='InnoDB'
                    )
    op.create_table('skill',
                    sa.Column('id', mysql.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('name', mysql.VARCHAR(
                        length=128), nullable=False),
                    sa.Column('description', mysql.TEXT(), nullable=False),
                    sa.Column('difficulty', mysql.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('contributor_id', mysql.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['contributor_id'], [
                        'user.id'], name='skill_ibfk_1'),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_collate='utf8mb4_0900_ai_ci',
                    mysql_default_charset='utf8mb4',
                    mysql_engine='InnoDB'
                    )
    op.create_index('name', 'skill', ['name'], unique=False)
    op.drop_table('recipe__tag')
    # ### end Alembic commands ###
