"""empty message

Revision ID: 2d7cb51b6698
Revises: c7004df51448
Create Date: 2022-06-12 00:47:43.992297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d7cb51b6698'
down_revision = 'c7004df51448'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='collection')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('name', 'collection', ['name'], unique=False)
    # ### end Alembic commands ###
