"""empty message

Revision ID: 9754ad4dc629
Revises: db4b3fa8b4e2
Create Date: 2022-06-23 17:56:46.549824

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9754ad4dc629'
down_revision = 'db4b3fa8b4e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tag_ibfk_1', 'tag', type_='foreignkey')
    op.drop_column('tag', 'recipe_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('recipe_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('tag_ibfk_1', 'tag', 'recipe', ['recipe_id'], ['id'])
    # ### end Alembic commands ###
