"""empty message

Revision ID: bbe4c8608ea6
Revises: 41747eb8d329
Create Date: 2022-06-17 01:09:15.740063

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bbe4c8608ea6'
down_revision = '41747eb8d329'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection__recipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('ingredient', 'hindi_name_latin',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ingredient', 'hindi_name_latin',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.drop_table('collection__recipe')
    # ### end Alembic commands ###
