"""empty message

Revision ID: db4b3fa8b4e2
Revises: 446283d2a9ce
Create Date: 2022-06-23 17:53:20.828943

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'db4b3fa8b4e2'
down_revision = '446283d2a9ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe__tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('skill__step')
    op.drop_index('name', table_name='skill')
    op.drop_table('skill')
    op.drop_constraint('tag_ibfk_1', 'tag', type_='foreignkey')
    op.drop_constraint('tag_ibfk_2', 'tag', type_='foreignkey')
    op.drop_column('tag', 'skill_id')
    op.drop_column('tag', 'recipe_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('recipe_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('tag', sa.Column('skill_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('tag_ibfk_2', 'tag', 'skill', ['skill_id'], ['id'])
    op.create_foreign_key('tag_ibfk_1', 'tag', 'recipe', ['recipe_id'], ['id'])
    op.create_table('skill',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=False),
    sa.Column('difficulty', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('contributor_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['contributor_id'], ['user.id'], name='skill_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 'skill', ['name'], unique=False)
    op.create_table('skill__step',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('recipe_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('serial_number', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('instruction', mysql.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['skill.id'], name='skill__step_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('recipe__tag')
    # ### end Alembic commands ###
